apiVersion: v1
kind: Pod
metadata:
  name: cowrie
  labels:
    app: cowrie  
spec:
  containers:
  - name: cowrie
    image: cowrie/cowrie:latest
    ports:
      - containerPort: 22
      - containerPort: 2222
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"  
  restartPolicy: Always
