apiVersion: v1
kind: Pod
metadata:
  name: mailoney
  labels:
    app: mailoney
spec:
  containers:
  - name: mailoney
    image: rduran02/honeyflow-mailoney:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 25
