apiVersion: v1
kind: Service
metadata:
  name: pod-service-mailoney
spec:
  type: NodePort
  selector:
    app: mailoney
  ports:
    - port: 8082  # Puerto que el Service expone externamente
      targetPort: 25  # Puerto interno al que apunta el Service
      nodePort: 30165  # Puerto en el nodo
  externalIPs:
    - 172.16.4.54 # IP externa a la que quieres asociar el Service