apiVersion: v1
kind: Service
metadata:
  name: pod-service-heralding
spec:
  type: NodePort
  selector:
    app: heralding
  ports:
    - port: 8083  # Puerto que el Service expone externamente
      targetPort: 80  # Puerto interno al que apunta el Service
      nodePort: 30166  # Puerto en el nodo
  externalIPs:
    - 172.16.4.54 # IP externa a la que quieres asociar el Service

